### ISSUE TITLE
Encode settings in URL?

### ISSUE THREAD

**Issue by tripu** [w3c/mailing-list-archives#24]
Similar to #18, but with the URL: on top of saving display options for the user in their cookies, push a new URL to the history every time an option is changed (thread view, Markdown formatting, extended headers, etc).

That way, the message can be shared or bookmarked including those display options.

This would make URLs longer and uglier, though:
eg, `https://lists.w3.org/Archives/Public/public-html-mail/2007May/0002.html?thread=on&headers=simple&formatting=md`

**Comment by gosko** [comment]
It may be tricky to implement, but I would prefer to minimize the amount of state we encode into the URIs like this. People pass these URIs around a lot and it may be annoying to be sent a pointer to a view of the archives that you dislike.

If we store user preferences in cookies, people can follow links to the usual URI ending in `0002.html` and our js lib can take care of presenting the message or thread in their preferred view. (flattened or not, thread tree visible or not)

If we do want to make a given view linkable, I think it might be better to store the state within URI fragments for better cacheability, e.g. `https://lists.w3.org/Archives/Public/public-html-mail/2007May/0002.html#view=threaded`

But I would prefer to omit these fragments from the history by default and only make them available when specifically requested via some kind of 'link to this view' permalink or some such. Cutting and pasting from the address bar should not include them by default, because that pushes the cutter's viewing preferences on the paster :)

**Comment by tripu** [comment]
Yes, I wasn't sure about adding view preferences to the URL either&hellip;

I like best your idea of having a &ldquo;permalink&rdquo; somewhere on the page, and only _that_ URI including explicit settings!
